### ISSUE TITLE
Filesystem structure is Java-style

### ISSUE THREAD

**Issue by DJ-Huntress** [M4Numbers/Walkers#1]
No need for a huge number of stacked directories.

Try having a look at these:
http://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application
http://as.ynchrono.us/2007/12/filesystem-structure-of-python-project_21.html

**Comment by J4Numbers** [comment]
Altered in accordance to less-stupid principles of design than my own.
